name: Setup env
description: Setup env

runs:
  using: 'composite'
  steps:
    - name: Add env file
      run:   |
        touch .env

        echo 'ULTRALIGHT_PATH=${{ env.ULTRALIGHT_PATH }}' >> .env
        echo 'DOTNET_ROOT=${{ env.DOTNET_PATH }}' >> .env

        if [ "$RUNNER_OS" == "Linux" ]; then
          echo 'DOTNET_INCLUDES="${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.linux-x64/8.0.2/runtimes/linux-x64/native"' >> .env
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ls -a /Users/runner/.dotnet/packs/Microsoft.NETCore.App.Host.osx-arm64
          ls -a /Users/runner/.dotnet/packs
          ls -a ${{ env.DOTNET_PATH }}
          ls -a ${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.osx-arm64/8.0.2/runtimes
          echo 'DOTNET_INCLUDES="${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.osx-arm64/8.0.2/runtimes/osx-arm64/native"' >> .env
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo 'DOTNET_INCLUDES="${{ env.DOTNET_PATH }}\\packs\\Microsoft.NETCore.App.Host.win-x64\\8.0.2\\runtimes\\win-x64\\native"' >> .env
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

# C:\\Program\ Files\\dotnet
# C:\\Program\ Files\\dotnet

# D:\\a\\dreich\\ultralight\\ultralight\\SDK
