name: Setup env
description: Setup env

runs:
  using: 'composite'
  steps:
    - name: Add env file
      run:   |
        touch .env

        echo 'ULTRALIGHT_PATH=${{ env.ULTRALIGHT_PATH }}' >> .env
        echo 'DOTNET_ROOT=${{ env.DOTNET_PATH }}' >> .env

        if [ "$RUNNER_OS" == "Linux" ]; then
          ls -a "${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.linux-x64"
          version=$(basename $(find ${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.linux-x64 -maxdepth 1 -type d -name "8.0*" | head -n 1))
          echo $version
          echo 'DOTNET_INCLUDES=${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.linux-x64/$version/runtimes/linux-x64/native' >> .env
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ls -a "${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.osx-arm64"
          version=$(basename $(find ${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.osx-arm64 -maxdepth 1 -type d -name "8.0*" | head -n 1))
          echo $version
          echo 'DOTNET_INCLUDES=${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.osx-arm64/$version/runtimes/osx-arm64/native' >> .env
        elif [ "$RUNNER_OS" == "Windows" ]; then
          ls -a "${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.win-x64"
          version=$(basename $(find ${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.win-x64 -maxdepth 1 -type d -name "8.0*" | head -n 1))
          echo $version
          echo 'DOTNET_INCLUDES=${{ env.DOTNET_PATH }}/packs/Microsoft.NETCore.App.Host.win-x64/$version/runtimes/win-x64/native' >> .env
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
