name: Setup .Net
description: Setup .Net

runs:
  using: 'composite'
  steps:
    - name: Set DOTNET_PATH
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "DOTNET_PATH=/usr/share/dotnet" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "DOTNET_PATH=/c/Program\ Files/dotnet" >> $GITHUB_ENV
          # echo "DOTNET_PATH=C:\\Program\ Files\\dotnet" >> $GITHUB_ENV
          # C:\\\Program\\ Files\\\dotnet
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "DOTNET_PATH=/Users/runner/.dotnet" >> $GITHUB_ENV
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
