name: Setup engine base
description: Setup engine base

runs:
  using: 'composite'
  steps:
    - name: Test
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install clang
          sudo apt-get install build-essential
          sudo apt-get install cmake
          sudo apt-get install make
          sudo apt install llvm
          export CC=clang
          export CXX=clang++
          clang -v
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo Windows
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install llvm
          brew install cmake
          brew install make
          export CC=clang
          export CXX=clang++
          clang -v
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Install conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.1.0

    - name: Create default profile
      shell: bash
      run: |
        export CC=clang
        export CXX=clang++
        conan profile detect

    - name: Config profile
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo Linux
          sudo apt-get update && sudo apt-get install build-essential
          sudo apt install clang
          clang -v
          conan profile show
          echo "
            [settings]
            arch=x86_64
            build_type=Debug
            compiler=clang
            compiler.cppstd=gnu17
            compiler.libcxx=libstdc++11
            compiler.version=11
            os=Linux
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
          " > /home/runner/.conan2/profiles/default
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo Windows
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo macOS
          conan remove "*" --locks --force
          brew install cmake
          brew install make
          brew install make
          brew install llvm
          clang -v
          conan profile show
          echo "
            [settings]
            arch=armv8
            build_type=Debug
            compiler=apple-clang
            compiler.cppstd=gnu17
            compiler.libcxx=libc++
            compiler.version=15
            os=Macos
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
          " > /Users/runner/.conan2/profiles/default
          conan profile show
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Install Linux staff
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install libxcb-util-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev
        fi
      shell: bash
