name: Setup base
description: Setup base

runs:
  using: "composite"
  steps:
    - uses: tecolicom/actions-install-and-cache@v1
      name: Install dependencies linux
      if: env.os == 'ubuntu-latest'
      with:
        run: |
          apt-get update
          apt-get install gcc g++ gdb clang build-essential llvm cmake libxcb-util-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev
        path: "/var/cache/apt/archives"
        cache: yes
        key: ${{ env.envHash }}-${{ env.os }}-apt-store
        sudo: true

    - uses: tecolicom/actions-install-and-cache@v1
      name: Install dependencies macos
      if: env.os == 'macos-14'
      with:
        run: |
          brew install p7zip llvm cmake conan
        path: $(brew --prefix)
        cache: yes
        key: ${{ env.envHash }}-${{ env.os }}-brew
        sudo: false

    - run: Set-MpPreference -DisableRealtimeMonitoring $true
      if: env.os == 'windows-latest'
      shell: powershell

    - name: Install dependencies windows
      if: env.os == 'windows-latest'
      shell: powershell
      run: |
        choco install make cmake 7zip yq
        choco install llvm --version=18.1.6

    - name: Setup wm
      shell: bash
      run: |
        mkdir -p $(pwd)/apps/usr/local/bin
        ls -a $(pwd)/apps/usr/local/bin
        echo "$(pwd)/apps/usr/local/bin" >> $GITHUB_PATH
        cd wm
        chmod +x config.sh
        ./config.sh
        echo "$(pwd)" >> $GITHUB_PATH
