name: Setup ultralight
description: Setup ultralight

runs:
  using: 'composite'
  steps:
    - name: Install ultralight
      if: env.os == 'ubuntu-latest'
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install p7zip-full
          sudo apt-get install clang
          sudo apt-get install build-essential
          sudo apt-get install cmake
          sudo apt-get install libxcb-util-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - name: Check if cache exists
      if: env.os == 'macos-14'
      id: cache-check
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/bin
        key: ${{ runner.os }}-brew

    - name: Restore cache
      if: env.os == 'macos-14' && steps.cache-check.outputs.cache-hit == 'true'
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/bin
        key: ${{ runner.os }}-brew
        restore-keys: |
          ${{ runner.os }}-brew

    - name: Install packages with Homebrew
      if: env.os == 'macos-14' && steps.cache-check.outputs.cache-hit != 'true'
      shell: bash
      run: |
          brew install p7zip
          brew install llvm
          brew install cmake
          which cmake

    - name: Save cache
      if: env.os == 'macos-14' && steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/bin
        key: ${{ runner.os }}-brew

    - name: Install ultralight
      if: env.os == 'windows-latest'
      shell: powershell
      run: |
        choco install make
        choco install cmake
        choco install llvm
        choco install 7zip
