name: Setup ultralight
description: Setup ultralight

runs:
  using: 'composite'
  steps:
    - uses: tecolicom/actions-install-and-cache@v1
      if: env.os == 'ubuntu-latest'
      with:
        run: 'apt-get install clang build-essential cmake libxcb-util-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev'
        path: '/var/cache/apt/archives'
        cache: yes
        key: '${{ runner.os }}-apt-store'
        sudo: true

    - uses: tecolicom/actions-install-and-cache@v1
      if: env.os == 'macos-14'
      with:
        run: 'brew install p7zip llvm cmake conan'
        path: $(brew --prefix)
        cache: yes
        key: '${{ runner.os }}-brew'
        sudo: false

    - uses: tecolicom/actions-install-and-cache@v1
      if: env.os == 'windows-latest'
      with:
        run: 'choco install make cmake llvm 7zip dotnet'
        path: 'c/ProgramData/chocolatey/lib'
        cache: yes
        key: '${{ runner.os }}-choco'
        sudo: false
