name: Setup base
description: Setup base

runs:
  using: 'composite'
  steps:
    - uses: tecolicom/actions-install-and-cache@v1
      name: Install dependencies linux
      if: env.os == 'ubuntu-latest'
      with:
        run: 'apt-get install clang build-essential cmake libxcb-util-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev apt-get install -y dotnet-sdk-8.0=8.0.3*'
        path: '/var/cache/apt/archives'
        cache: yes
        key: '${{ runner.os }}-apt-store'
        sudo: true

    - uses: tecolicom/actions-install-and-cache@v1
      name: Install dependencies macos
      if: env.os == 'macos-14'
      with:
        run: 'brew install p7zip llvm cmake conan dotnet@8 && which dotnet'
        path: $(brew --prefix)
        cache: yes
        key: '${{ runner.os }}-brew'
        sudo: false

# riznia

    # - uses: actions/cache/restore@v4
    #   if: env.os == 'windows-latest'
    #   with:
    #     path: C:\ProgramData\chocolatey\lib
    #     key: ${{ runner.os }}-choco

    # - uses: ./.github/workflows/utils/test
    #   if: env.os == 'windows-latest'
    #   with:
    #     run: 'echo here'
    #     path: /c/ProgramData/chocolatey/lib
    #     cache: yes
    #     key: ${{ runner.os }}-choco
    #     sudo: false

    - name: test
      if: env.os == 'windows-latest'
      shell: powershell
      run: |
        choco install make cmake llvm 7zip dotnet --version 8.0.3

    # - uses: ./.github/workflows/utils/test
    #   if: env.os == 'windows-latest'
    #   with:
    #     run: 'echo 1'
    #     path: C:\ProgramData\chocolatey\lib
    #     cache: yes
    #     key: ${{ runner.os }}-choco
    #     sudo: false

    # - uses: tecolicom/actions-install-and-cache@v1
    #   if: env.os == 'windows-latest'
    #   with:
    #     run: 'echo 1'
    #     path: c/ProgramData/chocolatey/lib
    #     cache: yes
    #     key: ${{ runner.os }}-choco
    #     sudo: false

    # - uses: actions/cache/save@v4
    #   if: env.os == 'windows-latest'
    #   with:
    #     path: C:\ProgramData\chocolatey\lib
    #     key: ${{ runner.os }}-choco


    # - uses: tecolicom/actions-install-and-cache@v1
    #   if: env.os == 'windows-latest'
    #   with:
    #     run: 'choco install make cmake llvm 7zip dotnet'
    #     path: '/c/ProgramData/chocolatey/lib'
    #     cache: yes
    #     key: '${{ runner.os }}-choco'
    #     sudo: false
