name: Setup ultralight
description: Setup ultralight

runs:
  using: 'composite'
  steps:
    - name: Set ULTRALIGHT_PATH
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "ULTRALIGHT_PATH=${{ env.projectRoot }}/ultralight" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "ULTRALIGHT_PATH=${{ env.projectRoot }}/ultralight/ultralight/SDK" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "ULTRALIGHT_PATH=${{ env.projectRoot }}/ultralight/SDK" >> $GITHUB_ENV
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        key: ${{ env.envHash }}-${{ env.os }}-ultralight
        path: ${{ env.ULTRALIGHT_PATH }}

    - name: Install ultralight
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && env.os != 'windows-latest'
      run: |
        cd ../
        mkdir ultralight
        cd ultralight

        if [ "$RUNNER_OS" == "Linux" ]; then
          wget https://ultralight-files.sfo3.cdn.digitaloceanspaces.com/ultralight-sdk-${{ env.ultralightVersion }}-linux-x64.7z
          7za x ultralight-sdk-1.3.0-linux-x64.7z
        elif [ "$RUNNER_OS" == "macOS" ]; then
          wget https://ultralight-files.sfo3.cdn.digitaloceanspaces.com/ultralight-sdk-${{ env.ultralightVersion }}-mac-arm64.7z
          7za x ultralight-sdk-1.4.0a-mac-arm64.7z

          echo -e "#include <Ultralight/String.h>\n$(cat SDK/include/Ultralight/ConsoleMessage.h )" > SDK/include/Ultralight/ConsoleMessage.h
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - name: Install ultralight
      if: steps.restore-cache.outputs.cache-hit != 'true' && env.os == 'windows-latest'
      shell: powershell
      run: |
        cd ../
        New-Item -ItemType Directory -Path ultralight
        cd ultralight

        Invoke-WebRequest -Uri https://ultralight-files.sfo3.cdn.digitaloceanspaces.com/ultralight-sdk-${{ env.ultralightVersion }}-win-x64.7z -OutFile ultralight-sdk.7z
        7z x ultralight-sdk.7z -o"ultralight"

    - uses: actions/cache/save@v4
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        key: ${{ env.envHash }}-${{ env.os }}-ultralight
        path: ${{ env.ULTRALIGHT_PATH }}
