name: Install UI dependencies
description: Install UI dependencies

runs:
  using: 'composite'
  steps:
    - name: Dependencies installation
      shell: bash
      run: cd ${{ env.uiRoot }} && pnpm install
