name: Install UI dependencies
description: Install UI dependencies

inputs:
  rootPath:
    description: Path to project root
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: "${{ env.pnpmPath }}"
        key: ${{ env.pnpmKeysPrefix }}${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.pnpmKeysPrefix }}

    - name: Dependencies installation
      shell: bash
      run: cd ${{inputs.rootPath}} && pnpm install
