name: Install dependencies UI
description: Install dependencies UI

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: cd ${{ env.uiRoot }} && pnpm install
