name: Install UI dependencies
description: Install UI dependencies

inputs:
  rootPath:
    description: Path to project root
    required: true
  pnpmPath:
    description: Path to pnpm cache
    required: true
  pnpmKeysPrefix:
    description: Prefix for pnpm cache
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Dependencies installation
      shell: bash
      run: echo ${{ inputs.pnpmPath }}

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ inputs.pnpmPath }}
        key: ${{ inputs.pnpmKeysPrefix }}${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ inputs.pnpmKeysPrefix }}

    - name: Dependencies installation
      shell: bash
      run: cd ${{inputs.rootPath}} && pnpm install
