name: Install UI dependencies
description: Install UI dependencies

inputs:
  rootPath:
    description: Path to project root
    required: true

runs:
  using: 'composite'
  steps:
    - name: Dependencies installation
      shell: bash
      run: cd ${{inputs.rootPath}} && pnpm install
