name: Lint engine
description: Lint engine

runs:
  using: 'composite'
  steps:
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './game/assets'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        inplace: true
