name: UI lint
description: UI lint

inputs:
  rootPath:
    description: Path to project root
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    - name: Set up base UI
      id: uiSetup
      uses: ./.github/actions/ui/base-setup

    - uses: ./.github/actions/ui/install-dependencies
      with:
        rootPath: ${{inputs.rootPath}}
        pnpmKeysPrefix: ${{steps.uiSetup.outputs.pnpmKeysPrefix}}
        pnpmPath: ${{steps.uiSetup.outputs.pnpmPath}}

    - name: Lint
      shell: bash
      run: cd ${{inputs.rootPath}} && pnpm lint:fix
