name: UI lint
description: UI lint

inputs:
  rootPath:
    description: Path to project root
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Set up base UI
    #   id: uiSetup
    #   uses: ./.github/workflows/modules/ui/base-setup

    # - uses: ./.github/workflows/modules/ui/install-dependencies
    #   with:
    #     rootPath: ${{inputs.rootPath}}
    #     pnpmKeysPrefix: ${{steps.uiSetup.outputs.pnpmKeysPrefix}}
    #     pnpmPath: ${{steps.uiSetup.outputs.pnpmPath}}
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Lint
      shell: bash
      run: cd ${{inputs.rootPath}} && pnpm lint:fix
