name: UI lint
description: UI lint

runs:
  using: 'composite'
  steps:
    - name: Setup base UI
      uses: ./.github/workflows/modules/ui/base-setup

    - uses: ./.github/workflows/modules/ui/install-dependencies

    - name: Lint
      shell: bash
      run: cd ${{ env.uiRoot }} && pnpm lint:fix
