name: UI lint
description: UI lint

inputs:
  rootPath:
    description: Path to project root
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up base UI
      id: uiSetup
      uses: ./.github/workflows/modules/ui/base-setup


    # - name: Install Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20

    # - uses: pnpm/action-setup@v3
    #   name: Install pnpm
    #   with:
    #     version: 8
    #     run_install: false
#
# steps.uiSetup.outputs.pnpmKeysPrefix
# steps.uiSetup.outputs.pnpmPath

#

    # - uses: actions/cache@v4
    #   name: Setup pnpm cache
    #   with:
    #     path: ${{ steps.uiSetup.outputs.pnpmPath}}
    #     key: ${{ steps.uiSetup.outputs.pnpmKeysPrefix }}${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ steps.uiSetup.outputs.pnpmKeysPrefix }}

    - uses: ./.github/workflows/modules/ui/install-dependencies
      with:
        rootPath: ${{inputs.rootPath}}
        pnpmKeysPrefix: ${{steps.uiSetup.outputs.pnpmKeysPrefix}}
        pnpmPath: ${{steps.uiSetup.outputs.pnpmPath}}

    # - name: Install dependencies
    #   shell: bash
    #   run: cd ${{inputs.rootPath}} && pnpm install

    - name: Lint
      shell: bash
      run: cd ${{ inputs.rootPath }} && pnpm lint:fix
