name: Install engine dependencies
description: Install engine dependencies

runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/utils/setup-base-libs

    - name: Install dependencies
      shell: bash
      run: |
        conan install . --update --build=missing
