name: Install engine dependencies
description: Install engine dependencies

inputs:
  buildSettings:
    description: Conan settings
    default: build_type=Debug

runs:
  using: 'composite'
  steps:
    - name: Install conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.1.0

    - name: Conan profile config
      shell: bash
      run: conan profile detect

    - name: Dependencies installation
      shell: bash
      run: conan install . --build=missing --settings=${{inputs.buildSettings}} -c tools.system.package_manager:mode=install
