name: Install engine dependencies
description: Install engine dependencies

inputs:
  buildSettings:
    description: Conan settings
    default: build_type=Debug

runs:
  using: 'composite'
  steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Dependencies installation
      shell: bash
      run: conan install . --build=missing --settings=${{inputs.buildSettings}}
