name: Install dependencies engine
description: Install dependencies engine

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        export CC=clang
        export CXX=clang++
        conan install . --update --build=missing
