name: Install engine dependencies
description: Install engine dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup conan cache
      uses: ./.github/workflows/utils/cache/get-conan-cache

    - name: Install dependencies
      shell: bash
      run: |
        export CC=clang
        export CXX=clang++
        conan install . --update --build=missing

    - name: Setup ultralight
      uses: ./.github/workflows/utils/setup-ultralight

    - name: Install Linux staff
      if: env.os == 'windows-latest'
      run:   |
        touch CMakeEnv.txt
        echo 'set(ENV{ULTRALIGHT_PATH} "D:\\a\\dreich\\ultralight\\ultralight\\SDK")' >> CMakeEnv.txt
        echo 'set(ENV{DOTNET_ROOT} "C:\\Program\ Files\\dotnet")' >> CMakeEnv.txt
        echo 'set(ENV{DOTNET_INCLUDES} "C:\\Program\ Files\\dotnet\\packs\\Microsoft.NETCore.App.Host.win-x64\\7.0.3\\runtimes\\win-x64\\native")' >> CMakeEnv.txt

        cat CMakeEnv.txt

        export CC=clang
        export CXX=clang++

        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="D:\a\dreich\dreich\build\Debug\generators\conan_toolchain.cmake" -S "D:\a\dreich\dreich" -B "D:\a\dreich\dreich\build\Debug"
        cmake --build "D:\a\dreich\dreich\build\Debug" --parallel 10 --target wind-asset-bundler

        cd build/Debug/wind/asset-pipeline
        sudo make install
        wind-asset-bundler -h
        cd ../../../../game/assets
        wind-asset-bundler --build ../.cache/
        cd ../../

        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="D:\a\dreich\dreich\build\Debug\generators\conan_toolchain.cmake" -S "D:\a\dreich\dreich" -B "D:\a\dreich\dreich\build\Debug"
        cmake --build "D:\a\dreich\dreich\build\Debug" --parallel 10 --target game

      shell: bash
