name: Install engine dependencies
description: Install engine dependencies

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        conan install . --update --build=missing
