name: Install engine dependencies
description: Install engine dependencies

inputs:
  buildSettings:
    description: Conan settings
    default: build_type=Debug

runs:
  using: 'composite'
  steps:
    - name: Setup conan cache
      uses: ./.github/workflows/utils/cache/get-conan-cache

    - name: Install dependencies
      shell: bash
      run: conan install . --update -s build_type=Debug --build=missing -c tools.system.package_manager:mode=install

    - name: Install Linux staff
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          # touch CMakeEnv.txt
          # echo 'set(ENV{ULTRALIGHT_PATH} "~/cpp-libs/ultralight-arm/SDK")' >> CMakeEnv.txt
          # echo 'set(ENV{DOTNET_ROOT} "/usr/local/share/dotnet")' >> CMakeEnv.txt
          # echo 'set(ENV{DOTNET_INCLUDES} "/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Host.osx-arm64/8.0.3/runtimes/osx-arm64/native")' >> CMakeEnv.txt
          # ls -a
          # pwd
          # cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=build/Debug/generators/conan_toolchain.cmake -S$(pwd) -B$(pwd)/build/Debug -G "Unix Makefiles"
          # cmake --build .
          echo test
        fi
      shell: bash
