name: Install dependencies scripts
description: Install dependencies scripts

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        echo "Hello world!"
