name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  contents: write
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/workflows/actions/ui/lint'
      - name: Scripts
        uses: './.github/workflows/actions/scripts/lint'
      - name: Engine
        uses: './.github/workflows/actions/engine/lint'
      - name: Linting commit
        uses: './.github/workflows/actions/commit'

  # testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Scripts
  #       uses: './.github/workflows/actions/scripts/test'
  #     - name: Engine
  #       uses: './.github/workflows/actions/engine/test'

  building:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/workflows/actions/ui/build'
      - name: Scripts
        uses: './.github/workflows/actions/scripts/build'
      - name: Engine
        uses: './.github/workflows/actions/engine/build'
