name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  base:
    uses: ./.github/workflows/base.yml

  ui:
    uses: ./.github/workflows/ui-ci.yml
    with:
      rootPath: 'game/assets/UI'

  engine:
    uses: ./.github/workflows/engine-ci.yml

  scripts:
    uses: ./.github/workflows/scripts-ci.yml

  # ciChecker:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: Check is CI valid
  #       if: needs.ci.outputs.isPassed != 'true'
  #       run: exit 1
