name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  contents: write
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/actions/ui/lint'
      - name: Scripts
        uses: './.github/actions/scripts/lint'
      - name: Engine
        uses: './.github/actions/engine/lint'
      - name: Linting commit
        uses: './.github/actions/commit'

  # testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Scripts
  #       uses: './.github/actions/scripts/test'
  #     - name: Engine
  #       uses: './.github/actions/engine/test'

  building:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/actions/ui/build'
      - name: Scripts
        uses: './.github/actions/scripts/build'
      - name: Engine
        uses: './.github/actions/engine/build'

  # base:
  #   uses: ./.github/workflows/base.yml

  # ui:
  #   needs: base
  #   uses: ./.github/workflows/ui.yml
  #   with:
  #     rootPath: 'game/assets/UI'

  # engine:
  #   needs: base
  #   uses: ./.github/workflows/engine.yml

  # scripts:
  #   needs: base
  #   uses: ./.github/workflows/scripts.yml

  # post:
  #   needs:
  #     - base
  #     - ui
  #     - engine
  #     - scripts
  #   uses: ./.github/workflows/post.yml

  # ciChecker:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: Check is CI valid
  #       if: needs.ci.outputs.isPassed != 'true'
  #       run: exit 1
