name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  base:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up main base
        id: uiSetup
        uses: ./.github/actions/base-setup/main
  # variables:
  #   uses: ./.github/workflows/variables.yml

  ui-ci:
    # needs: variables
    uses: ./.github/workflows/ui-ci.yml
    with:
      rootPath: 'game/assets/UI'
      # pnpmKeysPrefix: ${{needs.variables.outputs.pnpmKeysPrefix}}
      # pnpmPath: ${{needs.variables.outputs.pnpmPath}}

  engine-ci:
    # needs: variables
    uses: ./.github/workflows/engine-ci.yml

  scripts-ci:
    # needs: variables
    uses: ./.github/workflows/scripts-ci.yml

  # ciChecker:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: Check is CI valid
  #       if: needs.ci.outputs.isPassed != 'true'
  #       run: exit 1
