name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pages: write
  repository-projects: write
jobs:
  base:
    uses: ./.github/workflows/base.yml

  ui:
    uses: ./.github/workflows/ui.yml
    with:
      rootPath: 'game/assets/UI'

  engine:
    uses: ./.github/workflows/engine.yml

  scripts:
    uses: ./.github/workflows/scripts.yml

  # ciChecker:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: Check is CI valid
  #       if: needs.ci.outputs.isPassed != 'true'
  #       run: exit 1
