name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  contents: write
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/workflows/modules/ui/lint'
      - name: Scripts
        uses: './.github/workflows/modules/scripts/lint'
      - name: Engine
        uses: './.github/workflows/modules/engine/lint'
      - name: Linting commit
        uses: './.github/workflows/utils/commit'

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scripts
        uses: './.github/workflows/modules/scripts/test'
      - name: Engine
        uses: './.github/workflows/modules/engine/test'

  building:
    name: 'Build: ${{ matrix.config.name }}'
    runs-on: ${{ matrix.config.os }}
    # needs:
      # - linting
      # - testing
    strategy:
      fail-fast: false
      matrix:
        config:
          # - {
          #     name: 'Windows',
          #     artifact: 'Windows-MSVC.tar.xz',
          #     os: windows-latest,
          #     build_type: 'Release',
          #     cc: 'clang',
          #     cxx: 'clang++',
          #   }
          # - {
          #     name: 'Ubuntu',
          #     artifact: 'Linux.tar.xz',
          #     os: ubuntu-latest,
          #     build_type: 'Release',
          #     cc: 'clang',
          #     cxx: 'clang++',
          #   }
          - {
              name: 'MacOS',
              artifact: 'macOS.tar.xz',
              os: macos-latest,
              build_type: 'Release',
              cc: 'clang',
              cxx: 'clang++',
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: UI
        with:
          rootPath: 'game/assets/UI'
        uses: './.github/workflows/modules/ui/build'
      - name: Scripts
        uses: './.github/workflows/modules/scripts/build'
      - name: Engine
        uses: './.github/workflows/modules/engine/build'
        with:
          buildSettings: build_type=Debug
