name: dev

on:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  contents: write
jobs:
  # linting:
  #   name: Linting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: UI
  #       with:
  #         rootPath: 'game/assets/UI'
  #       uses: './.github/workflows/modules/ui/lint'
  #     - name: Scripts
  #       uses: './.github/workflows/modules/scripts/lint'
          # with:
          #   operating-system: 'ubuntu-latest'
  #     - name: Engine
  #       uses: './.github/workflows/modules/engine/lint'
  #     - name: Linting commit
  #       uses: './.github/workflows/utils/commit'

  # testing:
  #   name: 'Testing: ${{ matrix.config.name }}'
  #   runs-on: ${{ matrix.config.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       config:
  #         - {
  #             name: 'Windows',
  #             artifact: 'Windows.tar.xz',
  #             os: windows-latest,
  #             build_type: 'Release',
  #             cc: 'clang',
  #             cxx: 'clang++',
  #           }
  #         - {
  #             name: 'Ubuntu',
  #             artifact: 'Linux.tar.xz',
  #             os: ubuntu-latest,
  #             build_type: 'Release',
  #             cc: 'clang',
  #             cxx: 'clang++',
  #           }
  #         - {
  #             name: 'MacOS',
  #             artifact: 'macOS.tar.xz',
  #             os: macos-14,
  #             build_type: 'Release',
  #             cc: 'clang',
  #             cxx: 'clang++',
  #           }
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Scripts
  #       uses: './.github/workflows/modules/scripts/test'
  #       with:
  #         operating-system: 'ubuntu-latest'
  #     - name: Engine
  #       uses: './.github/workflows/modules/engine/test'

  building:
    name: 'Build: ${{ matrix.config.name }}'
    runs-on: ${{ matrix.config.os }}
    # needs:
    #   - linting
    #   - testing
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: 'Windows',
              artifact: 'Windows.tar.xz',
              os: windows-latest,
              buildType: 'Release',
              uiRoot: game/assets/UI,
              scriptRoot: game/assets/scripts,
              engineRoot: '/',
              # cc: 'clang',
              # cxx: 'clang++',
            }
          - {
              name: 'Ubuntu',
              artifact: 'Linux.tar.xz',
              os: ubuntu-latest,
              buildType: 'Release',
              uiRoot: game/assets/UI,
              scriptRoot: game/assets/scripts,
              engineRoot: '/',
              # cc: 'clang',
              # cxx: 'clang++',
            }
          - {
              name: 'MacOS',
              artifact: 'macOS.tar.xz',
              os: macos-latest,
              buildType: 'Release',
              uiRoot: game/assets/UI,
              scriptRoot: game/assets/scripts,
              engineRoot: '/',
              # cc: 'clang',
              # cxx: 'clang++',
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ENV
        run: |
          echo "name=${{ matrix.config.name }}" >> $GITHUB_ENV
          echo "artifact=${{ matrix.config.artifact }}" >> $GITHUB_ENV
          echo "os=${{ matrix.config.os }}" >> $GITHUB_ENV
          echo "buildType=${{ matrix.config.buildType }}" >> $GITHUB_ENV
          echo "uiRoot=${{ matrix.config.uiRoot }}" >> $GITHUB_ENV
          echo "scriptRoot=${{ matrix.config.scriptRoot }}" >> $GITHUB_ENV
          echo "engineRoot=${{ matrix.config.engineRoot }}" >> $GITHUB_ENV
      - name:
        shell: bash
        run: |
          echo ${{env.name}}
          echo ${{env.artifact}}
          echo ${{env.os}}
          echo ${{env.buildType}}
          echo ${{env.uiRoot}}
          echo ${{env.scriptRoot}}
          echo ${{env.engineRoot}}
      - name: UI
        uses: './.github/workflows/modules/ui/build'
      - name: Scripts
        uses: './.github/workflows/modules/scripts/build'
      - name: Engine
        uses: './.github/workflows/modules/engine/build'
