name: post

on: workflow_call

jobs:
  ci:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commit linting changes
        uses: ./.github/actions/commit
        with:
          message: 'Linting changes from gh action'
