name: prod

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linting:
    name: "Linting ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu",
              projectRoot: "/home/runner/work/dreich",
              artifact: "dreich-linux-${{ github.event.pull_request.title }}",
              os: "ubuntu-latest",
              engineBuildType: "Release",
              engineRoot: "/home/runner/work/dreich/dreich",
              cc: "clang",
              cxx: "clang++",
              isRelease: true,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: LFS
        uses: "./.github/workflows/utils/lfs"
      - name: Env
        uses: "./.github/workflows/utils/json-to-env"
        with:
          json: ${{ toJSON(matrix.config) }}
      - name: Engine
        uses: "./.github/workflows/modules/engine/lint"
      - name: Linting commit
        uses: "./.github/workflows/utils/commit"

  testing:
    name: "Testing: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "MacOS",
              projectRoot: "/Users/runner/work/dreich",
              artifact: "dreich-macos-${{ github.event.pull_request.title }}",
              os: "macos-14",
              engineBuildType: "Release",
              engineRoot: "/Users/runner/work/dreich/dreich",
              cc: "clang",
              cxx: "clang++",
              isRelease: true,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: LFS
        uses: "./.github/workflows/utils/lfs"
      - name: Env
        uses: "./.github/workflows/utils/json-to-env"
        with:
          json: ${{ toJSON(matrix.config) }}
      - uses: ./.github/workflows/utils/setup-base-libs
      - name: Engine
        uses: "./.github/workflows/modules/engine/test"

  building:
    name: "Build: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    needs:
      - linting
      - testing
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows",
              projectRoot: "D:/a/dreich",
              artifact: "dreich-windows-${{ github.event.pull_request.title }}",
              os: "windows-latest",
              engineBuildType: "Release",
              engineRoot: "D:/a/dreich/dreich",
              cc: "clang",
              cxx: "clang++",
              isRelease: true,
            }
          - {
              name: "Ubuntu",
              projectRoot: "/home/runner/work/dreich",
              artifact: "dreich-linux-${{ github.event.pull_request.title }}",
              os: "ubuntu-latest",
              engineBuildType: "Release",
              engineRoot: "/home/runner/work/dreich/dreich",
              cc: "clang",
              cxx: "clang++",
              isRelease: true,
            }
          - {
              name: "MacOS",
              projectRoot: "/Users/runner/work/dreich",
              artifact: "dreich-macos-${{ github.event.pull_request.title }}",
              os: "macos-14",
              engineBuildType: "Release",
              engineRoot: "/Users/runner/work/dreich/dreich",
              cc: "clang",
              cxx: "clang++",
              isRelease: true,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: LFS
        uses: "./.github/workflows/utils/lfs"
      - name: Env
        uses: "./.github/workflows/utils/json-to-env"
        with:
          json: ${{ toJSON(matrix.config) }}
      - uses: ./.github/workflows/utils/setup-base-libs
      - name: Engine
        uses: "./.github/workflows/modules/engine/build"
