name: ui-ci

on:
  workflow_call:
    inputs:
      pnpmPath:
        required: true
        type: string
      pnpmKeysPrefix:
        required: true
        type: string
    outputs:
      isBuildPassed:
        value: ${{jobs.ci.outputs.isBuildPassed}}
      isLintPassed:
        value: ${{jobs.ci.outputs.isLintPassed}}
      isPassed:
        value: ${{jobs.ci.outputs.isPassed}}

jobs:
  ci:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/base-setup/ui

      - uses: ./.github/actions/install-dependencies/ui
        with:
          pnpmKeysPrefix: ${{inputs.pnpmKeysPrefix}}
          pnpmPath: ${{inputs.pnpmPath}}

      - name: Lint
        id: lint
        run: pnpm lint

      - name: Build
        id: build
        run: pnpm build

    outputs:
      isBuildPassed: ${{steps.build.outcome == 'success'}}
      isLintPassed: ${{steps.lint.outcome == 'success'}}
      isPassed: ${{steps.build.outcome == 'success' && steps.lint.outcome == 'success'}}
