name: ui-ci

on:
  workflow_call:
    inputs:
      rootPath:
        required: true
        type: string
    outputs:
      isBuildPassed:
        value: ${{jobs.ci.outputs.isBuildPassed}}
      isLintPassed:
        value: ${{jobs.ci.outputs.isLintPassed}}
      isPassed:
        value: ${{jobs.ci.outputs.isPassed}}

jobs:
  ci:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up base UI
        id: uiSetup
        uses: ./.github/actions/base-setup/ui

      - uses: ./.github/actions/install-dependencies/ui
        with:
          rootPath: ${{inputs.rootPath}}
          pnpmKeysPrefix: ${{steps.uiSetup.outputs.pnpmKeysPrefix}}
          pnpmPath: ${{steps.uiSetup.outputs.pnpmPath}}

      - name: Lint
        id: lint
        run: cd ${{inputs.rootPath}} && pnpm lint

      - name: Build
        id: build
        run: cd ${{inputs.rootPath}} && pnpm build

    outputs:
      isBuildPassed: ${{steps.build.outcome == 'success'}}
      isLintPassed: ${{steps.lint.outcome == 'success'}}
      isPassed: ${{steps.build.outcome == 'success' && steps.lint.outcome == 'success'}}
